#!/usr/bin/env bash
PHPCTL_DIR=$(dirname "$(realpath "$0")")
if [ -s .phpctl ]; then
    set -a
    . .phpctl
    set +a
fi

PHP_VERSION=${PHP_VERSION:-82}
PHPCTL_IMAGE=${PHPCTL_IMAGE:-opencodeco/phpctl:php$PHP_VERSION}
PHPCTL_TTY=${PHPCTL_TTY:--it}

for file in "$PHPCTL_DIR"/src/*.sh; do
    # shellcheck source=src/php.sh
    . "$file"
done

${1:-help} "${@:2}"
