#!/usr/bin/env bash
PHPCTL_DIR=$(dirname $(realpath $0))
if [ -s .phpctl ]; then
    set -a
    . .phpctl
    set +a
fi

PHP_VERSION=${PHP_VERSION:-83}
PHPCTL_IMAGE=${PHPCTL_IMAGE:-opencodeco/phpctl:php$PHP_VERSION}

for file in $PHPCTL_DIR/src/*.sh; do
    . $file
done

${1:-help} ${@:2}
