#!/usr/bin/env sh
: '
    This script file was generated by the phpctl bundle command.
    It is basically a wrapper around the docker run command.
    It is not intended to be edited, but feel free to do so (if you know what you are doing).
    Move this script file to somewhere in your PATH to make it available as a command.
    A good place would be /usr/local/bin.
'
docker run \
    -w /workdir \
    -v $PWD:/workdir \
    --net host \
    $(env | awk -F= '/^[[:alpha:]]/{print $1}' | sed 's/^/-e/') \
    --rm -it IMAGE $@
